development:
  adapter: postgresql
  encoding: utf8
  database: cpobaby_development
  pool: 5
  username: 
  password: 

test:
  adapter: postgresql
  encoding: utf8
  database: cpobaby_test
  pool: 5
  username: 
  password: 